### ISSUE TITLE
[CRITICAL] Code repeat

### ISSUE THREAD

**Issue by ale1313** [Alexander-Lancellott/GitHub#21]
Como ves, tenemos una línea de código que se repite muchas veces, y esto es indeseado cuando se realiza un código. Intenta separar el código para hacerlo flexible ante un cambio y no repetir código. HINT: las funciones generalmente se usan para este propósito.
https://github.com/Alexander-Lancellott/GitHub/blob/03e5b93954383ab0ebb9747a3123d354e0df6d15/practica10rept.html#L22

**Comment by Alexander-Lancellott** [comment]
bueno
