### ISSUE TITLE
[CRITICAL] Counter initialized with -1

### ISSUE THREAD

**Issue by ale1313** [Alexander-Lancellott/GitHub#24]
No entiendo el por qué inicializaste el contador en -1, debería funcionarte correctamente sin necesidad de empezar con dicho valor.
https://github.com/Alexander-Lancellott/GitHub/blob/03e5b93954383ab0ebb9747a3123d354e0df6d15/practica1rept.html#L18

**Comment by Alexander-Lancellott** [comment]
esto se debía a la falta de validación de la variable "notas" produciendo que se sume la variable "c" cuando no era necesario
